"use strict";

/**
 * replyTracker — detecta respuestas (inbound) a las campañas leyendo la
 * bandeja de manager@rubencoton.com vía Gmail API.
 *
 * Lógica:
 *   1. Cada N minutos, lee los mensajes de Gmail con label INBOX y
 *      newer_than:7d.
 *   2. Para cada mensaje: mira si el In-Reply-To o References contiene
 *      un Message-Id con dominio @rubencoton.com (los que genera
 *      nuestro motor).
 *   3. Extrae el campaignId del Message-Id (formato "jobid-ts-rand@dom"
 *      donde jobid incluye campaignId implícitamente, alternativamente
 *      miramos el From del reply y buscamos recipient en snapshot).
 *   4. Registra evento { type: "reply", campaignId, email, snippet }.
 */

const { clients, isGoogleReady } = require("./googleHub");

/* P1 UX 2026-05-08 (petición usuario): bajado de 10min → 2min para que
 * los bounces (Mail Delivery Subsystem) se vayan a papelera con menos
 * latencia. Antes, se acumulaban 30+ bounces en INBOX entre scan y scan
 * saturando la bandeja de manager@. Coste: ~30 llamadas/h a Gmail API,
 * muy por debajo del rate limit (250 quota units/usuario/seg). */
const CHECK_INTERVAL_MS = Number(process.env.REPLY_TRACKER_INTERVAL_MS) || 2 * 60 * 1000; /* 2 min */
const LOOKBACK_DAYS = Number(process.env.REPLY_TRACKER_LOOKBACK_DAYS) || 7;

let _ticker = null;
let _dataStoreRef = null;

async function scanReplies() {
  if (!isGoogleReady()) return { ok: false, reason: "gmail_not_ready" };
  if (!_dataStoreRef) return { ok: false, reason: "no_datastore" };
  const gmail = clients.gmail();
  try {
    /* P0 FIX 2026-05-08 (peticion usuario "los rebotes me siguen saliendo"):
       el filtro automatico del usuario en Gmail mueve los mailer-daemon a la
       etiqueta personalizada "7-NOTIFICACIONES" y los SACA del INBOX.
       La query antes era `in:inbox` → no los pillaba → 154+ acumulados.
       Ahora ampliamos a:
       - in:inbox (replies humanos siguen aqui)
       - OR from:mailer-daemon/postmaster/etc (bounces dondequiera que esten,
         excepto papelera/spam que ya estan fuera).
       maxResults subido a 100 para limpiar acumulados rapido. */
    const list = await gmail.users.messages.list({
      userId: "me",
      q: `(in:inbox OR from:mailer-daemon OR from:postmaster OR from:mail-daemon) newer_than:${LOOKBACK_DAYS}d -from:manager@rubencoton.com -in:trash -in:spam`,
      maxResults: 100
    });
    const msgs = list.data.messages || [];
    if (!msgs.length) return { ok: true, scanned: 0, registered: 0 };

    /* P0 UX 2026-05-05 (peticion usuario): detectar bounces y moverlos a
     * PAPELERA para no saturar INBOX. BLINDAJE 2026-05-05 v2: solo borrar si
     * el SENDER es 100% identificable como sistema automatico de delivery.
     * Si solo coincide subject sin sender automatico → NO borrar (puede ser
     * respuesta humana con asunto similar). Ningun reply humano se elimina. */
    const isBounceSender = (sender) =>
      /(^|[<\s])(mailer-daemon|postmaster|mail-daemon|delivery-daemon|bounce[-+]|noreply[-+_.]*(delivery|bounce|mail))/i.test(sender || "");
    const isBounceSubject = (subj) =>
      /delivery (status notification|failure)|undelivered mail|mail delivery (failed|failure)|returned mail|failure notice|undeliverable|no se ha podido entregar|correo no entregado|el mensaje se ha bloqueado|se ha bloqueado|message blocked|message has been blocked|tu mensaje (no )?(ha sido|fue) (bloqueado|rechazado)/i.test(subj || "");
    /* Bounce confirmado: SENDER automatico (mailer-daemon, postmaster, etc.).
     * Subject solo aplica como BOOST si tambien hay Auto-Submitted: auto-replied
     * (que indica que el sistema lo genero automaticamente). */
    const isConfirmedBounce = (sender, subj, autoSub) => {
      if (isBounceSender(sender)) return true; /* sender de sistema automatico */
      const isAutoGenerated = /auto-(replied|generated)/i.test(autoSub || "");
      return isAutoGenerated && isBounceSubject(subj); /* subject + auto-flag */
    };

    const campaigns = _dataStoreRef.listAllCampaigns ? _dataStoreRef.listAllCampaigns() : _dataStoreRef.listCampaigns();
    /* Index por email de recipient → array de campañas recientes */
    const byRecipient = new Map();
    for (const c of campaigns) {
      if (!["sent", "completed", "sending"].includes(c.status)) continue;
      for (const r of (c.recipientsSnapshot || [])) {
        const e = String(r.email || "").toLowerCase();
        if (!e) continue;
        if (!byRecipient.has(e)) byRecipient.set(e, []);
        byRecipient.get(e).push(c);
      }
    }

    let registered = 0;
    let authErrorCount = 0;
    for (const m of msgs) {
      /* P0 FIX 2026-05-07: si OAuth expira mid-loop, abortar el scan
       * con código auth_expired en lugar de seguir tragando errores
       * silenciosamente. Igual al bug del __hardCounter que coloó 18h. */
      if (authErrorCount >= 3) {
        console.warn(`[replyTracker] AUTH expirado tras ${authErrorCount} 401s consecutivos. Abortando scan.`);
        return { ok: false, registered, reason: "auth_expired" };
      }
      try {
        const get = await gmail.users.messages.get({
          userId: "me",
          id: m.id,
          format: "metadata",
          metadataHeaders: ["From", "Subject", "In-Reply-To", "References", "Message-Id", "Date", "Auto-Submitted", "X-Autorespond", "X-Autoreply", "Precedence", "X-Failed-Recipients"]
        });
        const headers = Object.fromEntries((get.data.payload?.headers || []).map((h) => [h.name.toLowerCase(), h.value]));
        const from = String(headers["from"] || "");
        const subject = String(headers["subject"] || "");
        const fromEmail = (from.match(/<([^>]+)>/) || from.match(/([^\s<>]+@[^\s<>]+)/) || [])[1];
        const senderEmail = String(fromEmail || "").toLowerCase().trim();
        if (!senderEmail) continue;

        /* DETECCION BOUNCE BLINDADA: solo movemos a papelera si SENDER es
         * sistema automatico (mailer-daemon, postmaster, bounce-daemon).
         * Subject "blocked"/"failed" solo cuenta si tambien Auto-Submitted
         * indica que es generado automatico. Asi NO eliminamos respuestas
         * humanas reales aunque su subject mencione "blocked" o similar. */
        const autoSubHeader = String(headers["auto-submitted"] || "");
        if (isConfirmedBounce(senderEmail, subject, autoSubHeader)) {
          try {
            await gmail.users.messages.trash({ userId: "me", id: m.id });
            /* Intentar extraer email destinatario fallido (X-Failed-Recipients
             * suele venir en bounces) para registrar bounce en campana. */
            const failedTo = String(headers["x-failed-recipients"] || "").trim().toLowerCase();
            if (failedTo && byRecipient.has(failedTo)) {
              const targetCamp = (byRecipient.get(failedTo) || [])
                .slice()
                .sort((a, b) => new Date(b.sentAt || 0) - new Date(a.sentAt || 0))[0];
              if (targetCamp) {
                _dataStoreRef.addEvent({
                  type: "bounce",
                  campaignId: targetCamp.id,
                  email: failedTo,
                  source: "gmail_inbox_bounce_scan",
                  metadata: {
                    gmailMessageId: m.id,
                    subject: subject.slice(0, 200),
                    senderDaemon: senderEmail
                  },
                  occurredAt: new Date(Number(get.data.internalDate || Date.now())).toISOString()
                });
                /* Writeback rebotado en hoja CRM.
                 * P0 audit 2026-05-05: usar listContacts({search}) en vez
                 * de listContacts({}) (carga TODOS los 56k contactos en
                 * cada bounce). El parámetro search filtra por email/nombre
                 * antes de devolver. */
                try {
                  const sheetsWriteback = require("./sheetsWriteback");
                  const matching = _dataStoreRef.listContacts({ search: failedTo }) || [];
                  const c = matching.find((x) => String(x.email || "").toLowerCase() === failedTo);
                  if (c) {
                    let meta = c.customFields?._sheetMeta || c.custom?._sheetMeta;
                    if (typeof meta === "string") { try { meta = JSON.parse(meta); } catch (_e) { meta = null; } }
                    if (meta) sheetsWriteback.enqueue(meta, "rebotado", failedTo);
                  }
                } catch (_e) { /* swallow */ }
              }
            }
            console.log(`[replyTracker] bounce a papelera: from=${senderEmail} failed=${failedTo || "?"} | ${subject.slice(0,60)}`);
          } catch (e) {
            console.warn(`[replyTracker] no se pudo borrar bounce ${m.id}: ${e.message}`);
          }
          continue;
        }

        /* P0 audit 2026-05-01: filtrar AUTORESPONDERS (out-of-office,
         * vacation, autoreply). RFC 3834 + heurística de Subject. Antes
         * estos contaban como "reply" inflando stats de conversión. */
        const autoSubmitted = String(headers["auto-submitted"] || "").toLowerCase();
        const xAutoreply = headers["x-autorespond"] || headers["x-autoreply"];
        const precedence = String(headers["precedence"] || "").toLowerCase();
        const subjectLower = String(headers["subject"] || "").toLowerCase();
        const subjectAutoresponder = /^(re:?\s*)?(automatic reply|out of office|out-of-office|vacation|automatically generated|auto-?response|fuera de la oficina|fuera de oficina|vacaciones|respuesta autom[aá]tica)/i.test(subjectLower);
        if (autoSubmitted && autoSubmitted !== "no" || xAutoreply || precedence === "bulk" || precedence === "auto_reply" || subjectAutoresponder) {
          continue;
        }

        const inReplyTo = String(headers["in-reply-to"] || "");
        const references = String(headers["references"] || "");
        const relevantHeader = (inReplyTo + " " + references).toLowerCase();
        const looksLikeReply = relevantHeader.includes("@rubencoton.com");

        /* Matching por recipient: si el sender es un recipient de alguna
         * campaña, registramos reply aunque el header no esté. */
        const matchedCampaigns = byRecipient.get(senderEmail) || [];

        if (!looksLikeReply && !matchedCampaigns.length) continue;

        /* P0 FIX 2026-05-06 (peticion usuario "indicador respuestas no es certero"):
         * filtro anti-auto-reply. Out-of-office, vacaciones, "fuera de la oficina"
         * NO son respuestas reales. Detectamos por:
         *   - Header Auto-Submitted: auto-replied (RFC 3834)
         *   - X-Autorespond, X-Autoreply, Precedence: bulk/auto
         *   - Subject con patrones de ausencia
         * Si es auto-reply: skip (no se cuenta como reply). */
        const arAutoSub = String(headers["auto-submitted"] || "").toLowerCase();
        const arXAutoresp = String(headers["x-autorespond"] || "");
        const arXAutoreply = String(headers["x-autoreply"] || "");
        const arPrecedence = String(headers["precedence"] || "").toLowerCase();
        const isAutoReplyHeader = arAutoSub.includes("auto-replied") ||
                                  arAutoSub.includes("auto-generated") ||
                                  Boolean(arXAutoresp) ||
                                  Boolean(arXAutoreply) ||
                                  arPrecedence === "auto_reply" ||
                                  arPrecedence === "junk";
        const isAutoReplySubject = /(out[- ]of[- ]office|out of the office|fuera de (la )?oficina|estoy de vacaciones|estare de vacaciones|estoy ausente|fuera del despacho|en estos momentos no me encuentro|no estare disponible|de vacaciones hasta|ausencia|automatic reply|respuesta automatica|aviso de ausencia|notificacion de ausencia)/i.test(subject || "");
        if (isAutoReplyHeader || isAutoReplySubject) {
          /* Es auto-reply: NO contar como reply real. Salta sin loggear (es comun). */
          continue;
        }

        /* Elegir la campaña más reciente del recipient */
        const targetCampaign = matchedCampaigns
          .slice()
          .sort((a, b) => new Date(b.sentAt || 0) - new Date(a.sentAt || 0))[0];
        if (!targetCampaign) continue;

        /* Idempotencia: si ya registramos un reply de este gmail message id,
         * no lo duplicamos. Usamos metadata.gmailMessageId. */
        const store = _dataStoreRef.read();
        const already = store.events.find((ev) => ev.type === "reply" && ev.metadata?.gmailMessageId === m.id);
        if (already) continue;

        _dataStoreRef.addEvent({
          type: "reply",
          campaignId: targetCampaign.id,
          email: senderEmail,
          source: "gmail_inbox_scan",
          metadata: {
            gmailMessageId: m.id,
            gmailThreadId: get.data.threadId,
            subject: headers["subject"] || "",
            snippet: (get.data.snippet || "").slice(0, 200),
            receivedAt: headers["date"] || null
          },
          occurredAt: new Date(Number(get.data.internalDate || Date.now())).toISOString()
        });
        /* Writeback "respondido" en columna Merge status (verde oscuro
         * + texto blanco bold). Sobreescribe estados anteriores. */
        try {
          const sheetsWriteback = require("./sheetsWriteback");
          const all = _dataStoreRef.listContacts({ search: senderEmail });
          const c = (all || []).find((x) => String(x.email || "").toLowerCase() === senderEmail.toLowerCase());
          if (c) {
            let meta = c.customFields?._sheetMeta || c.custom?._sheetMeta;
            if (typeof meta === "string") { try { meta = JSON.parse(meta); } catch (_e) { meta = null; } }
            if (meta) sheetsWriteback.enqueue(meta, "respondido", senderEmail);
          }
        } catch (_e) { /* no fallar el scan por writeback */ }
        registered += 1;
      } catch (err) {
        /* P0 FIX 2026-05-07: detectar 401 (auth expirado) explícitamente.
         * Si vienen 3 seguidos, abortamos el scan. */
        const code = err.code || err.response?.status || 0;
        const msg = String(err.message || "");
        if (code === 401 || /invalid_grant|unauthoriz|invalid credentials/i.test(msg)) {
          authErrorCount += 1;
          console.warn(`[replyTracker] 401 en mensaje ${m.id}: ${msg.slice(0,80)} (acumulado ${authErrorCount})`);
        } else {
          console.warn("[replyTracker] error mensaje:", msg.slice(0, 200));
        }
      }
    }
    return { ok: true, scanned: msgs.length, registered, authErrors: authErrorCount };
  } catch (err) {
    /* Detectar 401 también en el catch externo (pre-loop) */
    const code = err.code || err.response?.status || 0;
    const msg = String(err.message || "");
    if (code === 401 || /invalid_grant|unauthoriz|invalid credentials/i.test(msg)) {
      console.error("[replyTracker] AUTH expirado pre-scan:", msg.slice(0,120));
      return { ok: false, error: msg, reason: "auth_expired" };
    }
    console.error("[replyTracker] scan error:", msg.slice(0,200));
    return { ok: false, error: msg };
  }
}

/* P1#3 audit 2026-04-30: flag de re-entry. Si Gmail API responde lento
 * (>10min con 50 mensajes y 429), corre dos scans paralelos → mismo
 * gmailMessageId chequea events.find antes de que el otro llame addEvent
 * → doble evento "reply". */
let _scanning = false;
const guardedScan = async () => {
  if (_scanning) return null;
  _scanning = true;
  try {
    return await scanReplies();
  } finally {
    _scanning = false;
  }
};

/* P0 FIX 2026-05-07: trackear también el firstTimer para evitar timers
 * huérfanos si start() se llama múltiples veces. */
let _firstTimer = null;

function start({ dataStore }) {
  if (_ticker || _firstTimer) return; /* idempotente */
  _dataStoreRef = dataStore;
  /* P0 FIX 2026-05-08 (peticion usuario): primera corrida en 20s en vez de
     2min. Si la app reinicia y hay bounces acumulados (etiqueta NOTIFICACIONES
     fuera de inbox), queremos limpiarlos lo antes posible para no saturar. */
  _firstTimer = setTimeout(() => {
    _firstTimer = null;
    guardedScan().then((r) => r && console.log("[replyTracker] first scan:", JSON.stringify(r))).catch(() => {});
  }, 20 * 1000);
  _firstTimer.unref?.();
  _ticker = setInterval(() => {
    guardedScan().then((r) => {
      if (r && r.registered > 0) console.log("[replyTracker]", JSON.stringify(r));
      /* P0 FIX 2026-05-07: si el scan reportó auth_expired, alertar */
      if (r && r.reason === "auth_expired") {
        console.error("[replyTracker] 🚨 AUTH EXPIRADO. Refrescar token OAuth manualmente.");
      }
    }).catch(() => {});
  }, CHECK_INTERVAL_MS);
  _ticker.unref?.();
  console.log(`[replyTracker] arrancado (scan cada ${Math.round(CHECK_INTERVAL_MS/60000)} min, lookback ${LOOKBACK_DAYS}d)`);
}

/* P1 UX 2026-05-08: scan on-demand. Permite gatillarlo manualmente al
 * arrancar la app (limpia bounces acumulados en el restart anterior)
 * o desde un endpoint admin si hace falta. Idempotente vía guardedScan. */
async function runOnce() {
  return guardedScan();
}

function stop() {
  if (_ticker) clearInterval(_ticker);
  if (_firstTimer) clearTimeout(_firstTimer);
  _ticker = null;
  _firstTimer = null;
}

module.exports = { start, stop, scanReplies, runOnce };
